#pragma once
#include"bbq_buzz.h"
#include"chilli_delight.h"
#include"crust.h"
#include"deepdish.h"
#include"fajita.h"
#include"flavours.h"
#include"focacia.h"
#include"italian.h"
#include"neapolitan.h"
#include"newyork.h"
#include"order.h"
#include"seekh_kebab.h"
#include"sicilian.h"
#include"stlouis.h"
#include"stuffed.h"
#include"The_cheese.h"
#include"tikka.h"
#include"veggie_delight.h"

